# Generated by Django 4.2.20 on 2025-05-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=2)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('verufy', models.IntegerField(default=0)),
                ('verufycode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'associator',
            },
        ),
    ]
