# Generated by Django 4.2.20 on 2025-05-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verify',
            field=models.IntegerField(default=0),
        ),
    ]
