# Generated by Django 4.2.20 on 2025-05-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20250509_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='verufy',
        ),
    ]
