# Generated by Django 4.2.20 on 2025-05-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField(default=0)),
                ('shipping', models.IntegerField(default=0)),
                ('grandtotal', models.IntegerField(default=0)),
                ('customname', models.CharField(max_length=50)),
                ('customemail', models.CharField(max_length=100)),
                ('customphone', models.CharField(max_length=15)),
                ('customaddress', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('fivecode', models.CharField(max_length=10, null=True)),
                ('paytype', models.CharField(max_length=10)),
                ('paymentype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('unitprice', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('dtotal', models.IntegerField(default=0)),
                ('dorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.ordermodel')),
            ],
        ),
    ]
