# Generated by Django 4.2.20 on 2025-04-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('discount', models.FloatField()),
                ('photo_url', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
